name: Java CI with Maven

on:
  push:
    paths:
    - '**.java'
    - '**.yml'
    - '**.pom'
  pull_request:
    paths:
    - '**.java'
    - '**.yml'
    - '**.pom'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Setting up Python for publishing
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: pip3 install requests # Request is needed for publishing over web hook
    
    - name: Publishing Build
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: python3 .github/workflows/scripts/publish.py ./target/AscensionMagnet-0.jar AscensionMagnet ${{ secrets.DiscordWebHook }} ${{ github.sha }}